CREATE TABLE "secret_folder" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "secret_folder_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" varchar(255) NOT NULL,
	"name" varchar(128) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	CONSTRAINT "folder_user_name_key" UNIQUE("userId","name")
);
--> statement-breakpoint
ALTER TABLE "secret_folder" ADD CONSTRAINT "secret_folder_userId_secret_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."secret_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "folder_user_idx" ON "secret_folder" USING btree ("userId");